# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3735c96b59031ebadf98ff3dfb679d45114590010a63f63e0eafef73f56eb1abe08c73f49d1f19d147aeaa0344a281220ccc77968c3eaebb2d6d63194b33e40c

test:
  secret_key_base: 71b0cad71feea922d54762e9bee726cfbd4e89d370d17e7aaca813da08a4aaf9f1143257727095c42a5980d16f23bc994b2dab8124910959e8e6ff42fa21ce7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
